Disable installing build-harness venv via python 2 (#51)
* Disable bh/venv for python 2 projects

* Specifically create a build harness Pipfile with the project's python version, if able to discover it

* Improve bh/venv messaging to include detected project version

* remove bh/ven 'not found' messaging when finding missing tools

diff --git a/Makefile.venv b/Makefile.venv
--- a/Makefile.venv
+++ b/Makefile.venv
@@ -6,6 +6,12 @@ BUILD_HARNESS_PIPFILE:=$(CURDIR)/$(BUILD_HARNESS_PIPFILE_NAME)
 BUILD_HARNESS_VENV_NAME:=.build-harness.venv
 BUILD_HARNESS_VENV:=$(CURDIR)/$(BUILD_HARNESS_VENV_NAME)
 WITH_BH_VENV=$(shell test -f $(BUILD_HARNESS_REQ) && echo "source $(BUILD_HARNESS_VENV)/bin/activate 2>/dev/null &&")
+LOCAL_PYTHON_VERSION=$(shell python -c 'import platform; ver=int(platform.python_version()[0]); print(ver)' 2>/dev/null)
+
+# This doesn't conform to extreme edge-use-cases of modules/python/Makefile.env, but should cover >99% of use.
+LOCAL_PROJECT_PYTHON_VERSION=$(shell if [ -e $(CURDIR)/Pipfile ]; then awk '/python_version*([0-9\.]*)/' Pipfile | awk 'match($$0, /[0-9\.]+/) {print substr($$0, RSTART, RLENGTH)}'; else echo ""; fi)
+LOCAL_PROJECT_PYTHON_VERSION_MAJOR=$(shell echo "$(LOCAL_PROJECT_PYTHON_VERSION)" | cut -c1)
+
 
 define which
 $(shell $(WITH_BH_VENV) which $1 2>/dev/null)
@@ -13,7 +19,12 @@ endef
 
 .PHONY: bh/venv/debug
 bh/venv/debug:
-	$(call print-var,VENV_MODULE)
+	$(call print-var,LOCAL_PYTHON_VERSION)
+	$(call print-var,LOCAL_PROJECT_PYTHON_VERSION)
+	$(call print-var,LOCAL_PROJECT_PYTHON_VERSION_MAJOR)
+	$(call print-var,BUILD_HARNESS_REQ)
+	$(call print-var,BUILD_HARNESS_VENV)
+	$(call print-var,BUILD_HARNESS_PIPFILE)
 	$(call print-var,BUMPVERSION)
 	$(call print-var,BLACK)
 	$(call print-var,ISORT)
@@ -26,27 +37,41 @@ $(BUILD_HARNESS_REQ_TEMPLATE):
 
 $(BUILD_HARNESS_REQ): $(BUILD_HARNESS_REQ_TEMPLATE)
 	@if [ -f $@ ]; then echo "Removing previously generated build-harness requirements" && rm $@; fi
-	@cat $(BUILD_HARNESS_REQ_TEMPLATE) | xargs -I % bash -c 'if [ -z "$$(which % 2>/dev/null)" ]; then echo "% not found" && echo "%" >> $@; fi'
+	@echo "Generating $@"
+	@cat $(BUILD_HARNESS_REQ_TEMPLATE) | xargs -I % bash -c 'if [ -z "$$(which % 2>/dev/null)" ]; then echo "%" >> $@; fi'
 
 $(BUILD_HARNESS_PIPFILE): $(BUILD_HARNESS_REQ)
 	@if [ -f $@ ]; then echo "Removing previously generated build-harness Pipfile" && rm $@; fi
 	@if [ -n "$$(which pipenv 2>/dev/null)" ]; then \
+		echo "Generating $@"; \
+		if [ -n "$(LOCAL_PROJECT_PYTHON_VERSION)" ]; then \
+			echo "[requires]" >> $@; \
+			echo "python_version = \"$(LOCAL_PROJECT_PYTHON_VERSION)\"" >> $@; \
+		fi; \
 		echo "[packages]" >> $@; \
 		cat $(BUILD_HARNESS_REQ) | xargs -I % bash -c 'if [ -z "$$(which % 2>/dev/null)" ]; then echo "% = \"*\"" >> $@; fi'; \
 	fi
 
 $(BUILD_HARNESS_VENV): $(BUILD_HARNESS_REQ) $(BUILD_HARNESS_PIPFILE)
-	@if [ -s $(BUILD_HARNESS_REQ) ]; then echo "Installing: $$(cat $(BUILD_HARNESS_REQ) | tr '\n' ' ')"; fi
+	@if [ $(LOCAL_PYTHON_VERSION) -eq 2 ]; then \
+		if [ $(LOCAL_PROJECT_PYTHON_VERSION_MAJOR) -eq 3 ]; then  \
+			echo "WARNING: Building a Python 3 project with Python 2."; \
+			echo "'It might..just..work.' - Carrot"; \
+		else \
+			echo "ERROR: Python $(LOCAL_PYTHON_VERSION) is unsupported by build-harness! Unable to install build-harness python dependencies automatically."; exit 1; \
+		fi; \
+	fi
+	@if [ -s $(BUILD_HARNESS_REQ) ]; then echo "Installing (Python $(LOCAL_PROJECT_PYTHON_VERSION) project via Python $(LOCAL_PYTHON_VERSION)): $$(cat $(BUILD_HARNESS_REQ) | tr '\n' ' ')"; fi
 	@if [ -n "$$(which pipenv 2>/dev/null)" ]; then \
 		echo "Installing build-harness requirements with pipenv..."; \
 		( \
-			$(shell if [ $$(python -c 'import platform; ver=int(platform.python_version()[0]); print(ver)' 2>/dev/null) -eq 2 ] && [ -n "$$(which python3 2>/dev/null)" ]; then echo "python3"; else echo "python"; fi) -m venv $@ \
+			if [ $(LOCAL_PYTHON_VERSION) -eq 2 ]; then virtualenv $@; else python -m venv $@; fi \
 			&& source $@/bin/activate && pip install -r <(PIPENV_PIPFILE=$(BUILD_HARNESS_PIPFILE) PIPENV_QUIET=1 pipenv --bare lock -r --pre) --ignore-installed \
 		); if [ $$? -ne 0 ]; then rm -rf $@; fi; \
 	else \
 		echo "WARNING: Installing build-harness requirements with venv + pip because pipenv was not installed..."; \
 		( \
-			$(shell if [ $$(python -c 'import platform; ver=int(platform.python_version()[0]); print(ver)' 2>/dev/null) -eq 2 ] && [ -n "$$(which python3 2>/dev/null)" ]; then echo "python3"; else echo "python"; fi) -m venv $@ \
+			if [ $(LOCAL_PYTHON_VERSION) -eq 2 ]; then virtualenv $@; else python -m venv $@; fi \
 			&& source $@/bin/activate && pip install -r $(BUILD_HARNESS_REQ) --ignore-installed \
 		); if [ $$? -ne 0 ]; then rm -rf $@; fi; \
 	fi
